# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Robyn Wright
email: robyn.wright@dal.ca
description: >- # this means to ignore newlines until "baseurl:"
  Hello! My name is Robyn Wright, and I am currently a Mitacs postdoctoral research fellow in the Langille Lab (Department of Pharmacology, Dalhousie University) and am researching the human microbiome in healthy and diseased individuals. I recently completed an Association of Commonwealth Universities Blue Charter Fellowship (October 2019-April 2020; School for Resources and Environmental Studies, Dalhousie University) in which I carried out a meta-analysis of all studies that characterise the microbial communities that colonise plastics - the "Plastisphere". I am interested in microbial community dynamics and interactions; how are these communities impacted by different factors of their environments? How do they change over time? What functions are they capable of carrying out?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://r-wright-1.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RobynJWright
github_username:  R-Wright-1

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
